name: {{ cookiecutter.project_name.lower().replace(' ', '_') }}
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytest
  - matplotlib
  - cartopy
  - cmocean
  - numpy
  - pandas
  - scipy
  - tqdm
  - xarray
  - netcdf4
  - palettable
  - dask
  - distributed
  - bottleneck
  - gsw
  - python-box
  - yaml
  - pip
  - pip:
    - pdoc
    - "-e /Users/gunnar/Projects/python/gvpy"
    - "-e ."
